meta_product_name: "Bee-Humans"
meta_title: "Service à la personne – Recevoir un service, avoir aidé quelqu'un d'autre. Un cycle vertueux"
meta_description: "En connectant les gens les uns aux autres, en étant satisfait d'avoir aidé quelqu'un avec ses propres compétences, et en trouvant toujours une personne prête à aider"
meta_image: "cover.png" # Doit exister dans `app/assets/images/`
meta_url: "https://bee-humans.xyz"
